Cukiernia/Controllers/ProduktyController.cs
using Cukiernia.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cukiernia.Controllers
{
    public class ProduktyController : Controller
    {
        private ProduktyContext db = new ProduktyContext();
        // GET: Produkty
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Lista(string nazwaKategori, string searchQuery = null)
        {
            var kategoria = db.Kategorie.Include("Produkt").Where(k => k.NazwaKategorii.ToUpper() == nazwaKategori.ToUpper()).Single(); //pobieramy kategoie i przekazujemy też produkty

            var produkty = kategoria.Produkt.Where(a => (searchQuery == null) ||
                                                   a.TytulProdukt.ToLower().Contains(searchQuery.ToLower()) ||
                                                   a.AutorProdukt.ToLower().Contains(searchQuery.ToLower()) &&
                                                   !a.Ukryty);
            if(Request.IsAjaxRequest())
            {
                return PartialView("_ProduktyList", produkty);
            }
            return View(produkty);
        }
        public ActionResult Szczegoly(int id)
        {
            var produkt = db.Produkty.Find(id);
            var name = User.Identity.Name;
          //  logger.Info("Strona szczególy | " + produkt.TytulKursu + " | " + name);
            return View(produkt);
        }


        [ChildActionOnly]  //Ta akcja moze byc wywolana tylko z poziomu innej akcji
       [OutputCache (Duration =60000)] //zapis dancyh z bazy do cache na 1 dzien
        public ActionResult KategorieMenu()
        {
            
            var kategorie = db.Kategorie.ToList();
            return PartialView("_KategorieMenu", kategorie);  //przekazujemy kategorie do widoku 
        }

        public ActionResult ProduktyPodpowiedzi(string term)
        {//pobiera produkty ograniczamy , nie moga byc ukryte.duze litery
            //pobieranie 5 produktow(podpowiedzi) i zwraca tylko label ,czyli info o producie
            //wykorzystujemy select by wziasc tytul produktu
            var produkty =this.db.Produkty.Where(a => !a.Ukryty && a.TytulProdukt.ToLower().Contains(term.ToLower()))
                .Take(5).Select(a => new { label = a.TytulProdukt });

            //zwracamy jako json
            return Json(produkty, JsonRequestBehavior.AllowGet);
        }
    }
}

Cukiernia/Views/Produkty/Lista.cshtml
@{
    ViewBag.Title = "Lista";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div id="ListaKategoriZawartosc">
    @Html.Action("KategorieMenu")
    <div id="KategorieListPrawaSekcja">
        <div id="Breadcrumb">
            <img src="../Content/Images/dommaly.png" />
            <a href="link">
                @Html.MvcSiteMap().SiteMapPath()
            </a>
            
            <form id="search-form" method="get" data-ajax="true" data-ajax-target="#SekcjaListaKategori">
                <input id="search-filter" type="search" name="searchQuery"
                       data-autocomplete-source="@Url.Action("ProduktyPodpowiedzi")"
                       placeholder="Wprowadź tekst, aby wyfiltrować..." />
                <input type="submit" value="" />
            </form>

        </div>
        <div id="SekcjaListaKategori">
            @Html.Partial("_ProduktyList")
        
    </div>
</div>

@section Scripts
{
@System.Web.Optimization.Scripts.Render("~/bundles/jqueryAndJqueryUI")
    <script>
        $(function () {
            
            var setupAutoComplete = function () {
                var $input = $(this);

                var options =
                    {
                        source: $input.attr("data-autocomplete-source"),
                        select: function (event, ui) {
                            $input = $(this);
                            $input.val(ui.item.label);
                            var $form = $input.parents("form:first");
                            $form.submit();
                        }
                    };

                $input.autocomplete(options);
            };
            var ajaxSubmit = function () {

                var $form = $(this);

                var settings = {
                    data: $(this).serialize(),
                    url: $(this).attr("action"),
                    type: $(this).attr("method")
                };

                $.ajax(settings).done(function (result) {
                    var $targetElement = $($form.data("ajax-target"));
                    var $newContent = $(result);
                    $($targetElement).replaceWith($newContent);
                    $newContent.effect("slide");
                });

                return false;
            };
           

            $("#search-filter").each(setupAutoComplete);
            $("#search-form").submit(ajaxSubmit);
        });;
    </script>
}

Cukiernia/Views/Produkty/Szczegoly.cshtml
@model Cukiernia.Models.Produkt
@using Cukiernia.Infrastructure

@{
    ViewBag.Title = "Szczegoly";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="ListaKategoriZawartosc">
   @Html.Action("KategorieMenu")
    <div id="KategorieListPrawaSekcja">
        <div id="Breadcrumb">
            <img src="../Content/Images/dommaly.png" />
            <a href="link">
                @Html.MvcSiteMap().SiteMapPath()
            </a>
        </div>
        <section id="SekcjaProdukt">
            <div id="ProduktLewa">
                <img src="@Url.ObrazkiSciezka(Model.NazwaPlikuObrazka)" />
            </div>
            <div id="ProduktPrawa">
                <div id="ProduktNazwa">
                    <h1>
                       @Model.TytulProdukt
                    </h1>
                    <h2>
                       @Model.AutorProdukt
                    </h2>
                </div>
                <div id="ProduktCena">
                    <div>
                       @string.Format("{0:0.##}", Model.CenaProdukt)<span>PLN</span>
                    </div>
                    <a href="@Url.Action("DodajDoKoszyka","Kozyk",new { id = Model.ProduktId })"></a>
                </div>
                <div id="ProduktOpis">
                    @Model.OpisProdukt
                </div>
                <div id="ProduktInfo">
                    @Model.OpisSkrocony
                </div>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <a href="@Url.Action("DodajProdukt", "Manage", new { produktId = Model.ProduktId })" style="margin-top: 20px; font-weight: bold; display: block;">Edytuj</a>
                }
            </div>
        </section>
    </div>
</div>

Cukiernia/Views/Produkty/_KategorieMenu.cshtml
@model IEnumerable<Cukiernia.Models.Kategoria>
@using Cukiernia.Infrastructure


<!--Kontrolka z kategoriami-->
<nav class="KategorieVertical">
    <ul>
        @foreach (var kategoria in Model)
        {
        <li>
            <a href="@Url.Action("Lista","Produkty",new { nazwaKategori =kategoria.NazwaKategorii.ToString() })" 
               style="background-image: url(@Url.IkonyKategoriiSciezka(kategoria.NazwaPlikuIkony); ">
                @kategoria.NazwaKategorii
            </a>
        </li>
        }
    </ul>
</nav>

Cukiernia/Views/Produkty/_ProduktyList.cshtml
@model IEnumerable<Cukiernia.Models.Produkt>
@using Cukiernia.Infrastructure

<div id="SekcjaListaKategori">
    
        <ul class="KursyTrzyKolumny MalaListaKategorii">
           
            @foreach (var produkt in Model) 
            {
                if (produkt.Ukryty == false)
                {
                        <li>
                            <article>
                                <a class="dodajDoKoszykaLink" href="@Url.Action("DodajDoKoszyka", "Koszyk", new { id = produkt.ProduktId })">
                                    <img src="@Url.Content("~/Content/Images/koszyk.png")" />
                                </a>
                                @if (produkt.Bestseller)
                    {
                                    <div class="bestsellerFlag"></div>
                                }

                                <a class="produktSzczegolyLink" href="@Url.Action("Szczegoly", "Produkty", new { id = produkt.ProduktId })">
                                    <img class="kurs" src="@Url.ObrazkiSciezka(produkt.NazwaPlikuObrazka)" />  <!--obrazki wywolanie dynamicznie-->
                                    <h1>
                                        @produkt.AutorProdukt - @produkt.TytulProdukt
                                    </h1>
                                </a>

                            </article>
                        </li>
                
                }
            }
        </ul>  
    </div>